[workspace]
members = ["src/*"]
default-members = ["src/wit-cli"]
resolver = "2"

[workspace.package]
readme = "README.md"

[workspace.dependencies]
git2 = {version = "0.18.1"}
clap = {version = "4.4.3"}