direction: down

scenario1 {
    style.fill: transparent
    style.stroke-dash: 5
    style.stroke: "#666"
    label: ""
    
    explanation: {
        style.stroke: transparent
        
        label: |txt
            Committing changes
        |
    }
    
    user.shape: person
    
    CLI_client: CLI
    
    user --> CLI_client: command: wit commit <message>
        
    
}

