vars {
    http-color: mediumpurple
    user-interaction-color: royalblue
    git-transport-color: orangered
}

classes {
    env: {
        style.stroke-dash: 1
        label.near: outside-top-center
        style.border-radius: 100
        style.fill: transparent
        style.double-border: false
        style.bold: false
        style.italic: true
    }
    legend: {
        label: Legend
        label.near: top-center
        style.fill: transparent
        style.underline: true
        grid-columns: 1
        grid-gap: 10
    }
    legend-line: {
        style.fill: transparent
        style.stroke: transparent
        label: ""
        grid-rows: 1
        grid-gap: 0
    }
    legend-dot: {
        style.stroke: transparent
        label: ""
        shape: rectangle
        width: 20
        height: 30
    }
    box: {
        style.fill: transparent
        style.stroke: transparent
        label: ""
    }
    note: {
        style.fill: transparent
        style.stroke: transparent
        style.text-transform: none
        style.font-size: 20
        style.font: null
    }
}