vars {
    ...@shared.vars
    d2-config {
        layout-engine: elk
    }
}

classes: {
    ...@shared.classes
    repository: {
        label.near: outside-top-center
        icon: https://icons.terrastruct.com/dev%2Fgit.svg
    }
    remote: {
        icon: https://icons.terrastruct.com/tech%2F022-server.svg
        label.near: outside-top-center
    }
    http: {
        style.stroke: ${http-color}
        style.font-color: ${http-color}
        style.border-radius: 60
        style.text-transform: none
    }
    ui: {
        style.stroke-dash: 1
        style.border-radius: 60
        style.text-transform: none
        style.stroke: ${user-interaction-color}
        style.font-color: ${user-interaction-color}
    }
    git-transport: {
        style.stroke: ${git-transport-color}
        style.font-color: ${git-transport-color}
        style.border-radius: 60
        style.text-transform: none
    }
}

direction: down

user-env: User Environment {
    class: env
    
    user: User {
        width: 100
        height: 120
        shape: person
        style.fill: ${user-interaction-color}
    }
    
    user -> browser: views wiki through {
        class: ui
    }
    user -> dev-env.cli: makes changes through {
        class: ui
    }
    browser -> _.remotes.remote1 {
        class: http
    }

    dev-env: Development Environment {
        class: env

        repository: Git Repository {
            class: repository
            icon.near: top-center

            submodule: Wit Submodule {
                class: repository
            }
            
            hooks: Git Hooks {
                class: repository
            }
        }

        cli: CLI Client{
            icon: https://uxwing.com/wp-content/themes/uxwing/download/web-app-development/cmd-terminal-icon.svg
        }

        cli -> _._.remotes.remote1.storage.repo: transports changes {
            class: git-transport
        }
        repository.hooks --> _._.remotes.remote1 {
            class: http
        }

        repository <- cli: writes changes {
            class: git-transport
        }
    }
    
    browser: Web Browser {
        icon: https://icons.terrastruct.com/dev%2Ffirefox.svg
    }
}

remotes: Remote Servers {
    class: env

    remote1: Server {
        class: remote
        icon.near: top-center

        storage: Storage {
            files: Files {
                shape: image
                height: 60
                icon: https://icons.terrastruct.com/essentials%2F257-file.svg
            }
            repo: Bare Repository {
                class: repository
            }
        }
    }
    remote2: Server {
        class: remote
    }
    remote3: Server {
        class: remote
    }
}

legend: {
    class: legend
    
    ui {
        class: legend-line
        git-circle {
            style.fill: ${user-interaction-color}
            class: legend-dot
        }
        note:|txt user interaction| {
            class: note
        }
    }
    
    http {
        class: legend-line
        http-circle {
            style.fill: ${http-color}
            class: legend-dot
        }
        note: |txt
        communication
        over HTTP(S)|{
            class: note
        }
    }
    
    git {
        class: legend-line
        git-circle {
            style.fill: ${git-transport-color}
            class: legend-dot
        }
        note:|md
        libgit2 transport
        (HTTPS or SSH)
        | {
            class: note
        }
    }
}