direction: down

devenv: Local Developer Environment {
    style.fill: transparent
    style.stroke-dash: 6
    style.stroke: gray

    user: User {
        shape: person 
        width: 100
        height: 120
    }
            
    cli: CLI utility {
        shape: square
    }
            
    user -> cli: uses
    user -> repo.submodule: writes changes to
    cli -> repo.submodule: acts on
    
    repo: Git Repository {
        shape: stored_data
        
        code1: ''
        code1.shape: stored_data
    
        code2: ''
        code2.shape: stored_data
    
        submodule: wit submodule
        submodule.shape: stored_data
        submodule.style.stroke: blue 
    }
}

devenv.cli --> remotes.remote1: synchronizes to

remotes: Remote servers {
    style.fill: transparent
    style.stroke-dash: 6
    shape: cloud

    remote1: Wit Server {
        shape: rectangle
        style.stroke: blue
        
        repo: wit repository
        repo.shape: stored_data
        repo.style.stroke: blue
    }
    remote2: Wit Server {
        shape: rectangle
        style.stroke: red

        repo: ''
        repo.shape: stored_data
        repo.style.stroke: red
    }
    remote3: Wit Server {
        shape: rectangle
        style.stroke: green

        repo: ''
        repo.shape: stored_data
        repo.style.stroke: green
    }
    remote1 <-> remote2: federated
    remote1 <-> remote3
}



