direction: up

remotes: Remote Servers {
    shape: cloud
    style.fill: transparent
    style.stroke-dash: 6

    server1: Wit Server {
        style.stroke: blue
    }

    server2: Wit Server {
        style.stroke: red
    }
    
    server3: Wit Server {
        style.stroke: green
    }
    
    server1 -> server3: gets remaining files from
    server1 -> server2
}

user: User {
    shape: person
}

browser: HTTP client {
    shape: square
}

user -> browser: views with
browser -> remotes.server1: connects to address of
